### ISSUE TITLE
No way to continue editing an assignment after creating a new policy

### ISSUE THREAD

**Issue by aaltaf3** [expertiza/expertiza#1436]
Currently, there is no way to go back to editing an assignment after creating a new late policy. 
1. When editing an assignment, click on the "Due dates" tab.
2. Click the "New late policy" link.
3. Click the "Back" link.

The user is directed to the list of policies, which links them to the "New late policy" page. The "Back" link on the "New late policy" page should direct the user to the "Due dates" tab so they can continue to edit the assignment.

**Comment by Natansh21** [comment]
Should there be a 'Back' button on the page '/late_policies' page (attached), since there is no direct way to go back to 'edit assignment' page? This is the page that is rendered once the late policy is successfully created.

![LatePolicyCreated](https://user-images.githubusercontent.com/43691204/69858426-f8961580-125f-11ea-861d-ca34d8698484.PNG)

**Comment by SaNPai23** [comment]
2 issues to solve: First, the back button on Create new late policy redirects to the index page for Late policies, should actually function as normal back button.h 
Second, once a late policy is created, it redirects to the late policies index(as expected), but there is no back button there.
Both fixed in Commit# 9fb340c476820b1562f73c36ebbef2b130e47972
