### ISSUE TITLE
Count of fields wrong in import

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#183]
When importing participants (or users), it is typical not to specify a password, but rather to have the system generate it.  But if you do that, Expertiza reports that each record in the file you are importing does not have enough records.  In order to get it to import the file, you need to add " ," to each record.

Expertiza should know that a password is optional, and accept files that have nothing in the password field.

**Comment by yangsong8** [comment]
When importing students accounts, we can leave the password column blank, but we do need to add an empty column (in plain file, it gonna be ",,").

**Comment by yangsong8** [comment]
E1656 rejected.

**Comment by efg** [comment]
Was part of E1775, which was not chosen.

**Comment by nikolaygtitov** [comment]
I used .csv file with two following entries:
xuserstudent | X Student | xstudent@ncsu.edu
yuserstudent | Y Student | ystudent@ncsu.edu

Where '|' is the Tab delimiter. Note that neither entry has password field in it. I used "Tab" as delimiter.
Import was successful and password was auto-generated. Does it need to be tested with plain text instead of .csv file?

Since it did not complaint about missing password field or wrong counts of field with .csv file, the issue can be closed.
