### ISSUE TITLE
Not able to revert to TA account after impersonating 

### ISSUE THREAD

**Issue by YunkaiXiao** [expertiza/expertiza#1961]
System: MacOS BigSur 11.2.3
Browser: Chrome 89.0.4389.128 
What happened: Logged in as TA and impersonated a student, not able to see the impersonate textbox and revert button afterwards
How to reproduce: Uncertain, possibly by logging in to a TA account the night before and impersonate the next morning. Suspect automatic logout on a session timeout? Shouldn't be able to click impersonate when that happens.

**Comment by efg** [comment]
We cannot reproduce this directly.  I can log in as me and then impersonate you.  Then I impersonate a student, and I can see the textbox and revert button.  But, I don't know if I would see the same thing if I logged in with your credentials.  Also, I don't know how waiting overnight would affect it.  I'm not aware of any automatic logout, unless that functionality is in the gems we are using.

Maybe the best way to check would be for us to get together in a Zoom session (3:30 MWF so it would be during the Expertiza meeting) and have you log in on my machine.  Or maybe log in on my machine the evening before so that any auto-logout would already have occurred.

What do you thinK/

**Comment by johnbumgardner** [comment]
Tried replicating on Firefox. Didn't experience a bug

**Comment by YunkaiXiao** [comment]
I’ll see if I could reproduce it on Chrome


On Jul 10, 2021, at 12:09 PM, John Bumgardner ***@***.***> wrote:

﻿

Tried replicating on Firefox. Didn't experience a bug

**Comment by johnbumgardner** [comment]
Kai did you find anything with this in Firefox?
