### ISSUE TITLE
Impossible for an instructor to edit a questionnaire

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2136]
When Jennifer Kidd (instructor 2062?) tried to edit Wikibook Lesson Draft_2016S, she was told that an instructor can't edit a rubric.  What?!

**Comment by johnbumgardner** [comment]
Instructor 2062 is unable to edit this rubric because wikibook lesson draft_2016S (id 370) is owned by super_administrator2, who has id=2. When we call access_allowed in questionnaire_controller.rb we fail because the current user is not an admin/super admin nor shares the same id as the user who created this specific questionnaire.
<img width="982" alt="image" src="https://user-images.githubusercontent.com/38589044/141702554-4b067380-45ad-405f-b32b-9731d07c996e.png">
