### ISSUE TITLE
Account Request Failure on Beta

### ISSUE THREAD

**Issue by johnbumgardner** [expertiza/expertiza#2227]
Account request sends invalid passwords. I can request an account correctly, both on beta and on the account request PR, which i will merge, but the app sends two emails both containing separate passwords. Need to reference code on master, which i believe works properly

**Comment by johnbumgardner** [comment]
@nnhimes can you review this?

**Comment by nnhimes** [comment]
Right now it:
1. Creates a new user
2. L30 in user.rb says to run email_welcome after_create. email_welcome calls send_mail_to_user the first time. Since user password is blank, L29 says to randomize_password. 
3. reset_password is called by users_controller:create, overwriting this password.
4. send_mail_to_user called again by users_controller:create. 

Neither of the passwords sent in emails work, meaning the password is either changed again later (not by the reset_password method though), or the password returned by reset_password and randomize_password is the encrypted one and not the unencrypted pass needed to login. 

I am removing the call to email_welcome after a user is created on line 30 to fix the duplicate email send, but the password problem still needs fixing.

**Comment by johnbumgardner** [comment]
Use both SHA1 match functions.
