### ISSUE TITLE
"Your scores" crashes for Final project (and design doc)

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2807]
I believe this is Assignment 1166.  I have tried for two students, vrani being the last, and both times I have gotten that error screen.

This is a serious error.  If it has not been reported before, students must not be checking their feedback.

**Comment by dinesh-pasupuleti** [comment]
We encountered a bug in Expertiza due to an `ActiveRecord::StatementInvalid` error, which reported `Mysql2::Error: Access denied for user 'expertizaRoot'@'152.14.199.156'`. This error occurred during a SQL query on the `score_views`. To resolve it, we dropped the existing view and created a new view using the current account, to ensure proper permissions and fixing the access issue.
