### ISSUE TITLE
The mechanism of quiz selection

### ISSUE THREAD

**Issue by Winbobob** [expertiza/expertiza#551]
The procedure of quiz selection is the same as review selection now. But we (@yangsong8 and I) think these two selections should not be independent. Since quiz is used to filter some inappropriate reviews (to establish a reviewers' "reputation"), we think student should take quizzes only on the artifacts which he or she has chosen, instead of on all the available artifacts.

**Comment by efg** [comment]
Yes, that is true.  Maybe Yang can help with that.  I would think we want a
procedure similar to assigning reviews: either the instructor can assign
the students to read specific pages and take the quiz, or students could
choose from a list like they do for reviews.  We should discuss the UI for
this at a meeting.

**Comment by yangsong8** [comment]
Fix view on creating quiz questions: 6de2a322750048cc38f32793c860a347bdebd764
Fix back-end code for quiz creation: 784a838f6bb16bc6201bfc999ace35286ecf8b07
Fix Fix candidate quiz list display: 5d0ac705abd22fe9f443e94f1ea285ff0285a048
Comment out student_quiz_controller.rb: 80a693619d5900567dfbdd13e702d34c4aa9a8ad
Please not that the "student_quiz_controller.rb" should be deleted. The reason that I comment it instead of delete it is to prevent this file get merged in again when we merge the final projects.

**Comment by yangsong8** [comment]
The view of essay grading (app/views/student_quizzes/grade_essays.html.erb) should be removed. I will delete this file after all the final projects in spring 2015 have been merged.
