### ISSUE TITLE
Format of import file missing for topics

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#719]
If I try to import topics, the import page gives me this message:
- The import process expects the following columns:

But it doesn't say what the columns are!  It used to.  Please revert the change to fix this bug.

**Comment by yangsong8** [comment]
Update:
![image](https://cloud.githubusercontent.com/assets/4420550/23171744/64255b64-f821-11e6-8c94-d85b54799a82.png)

I can see the expected fields, however, they are not correct because we now also have url and description.

Please refer to the import file format below on fixing this:

T1, topic1, 2, category1, description, https://github.com/expertiza/expertiza/pull/865
T2, topic2, 2, category2, description, https://github.com/expertiza/expertiza/pull/866
Tc, topic3, 3, category3, "description description description description, description description, description description description description description description description description", https://github.com/expertiza/expertiza/pull/867
